import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const cssPath = join(root, "src/style.css");
const css = readFileSync(cssPath, "utf8");
copyFileSync(cssPath, join(dist, "style.css"));

const escaped = JSON.stringify(css);
writeFileSync(
  join(root, "src/style-text.ts"),
  `/**
 * @license
 * Copyright (c) 2026 João Vitor Zeppe (zeppejoaovitor@gmail.com)
 * MIT-licensed: https://opensource.org/license/MIT
 */

/** Injected stylesheet text — generated by scripts/copy-css.mjs. Do not edit. */
export const ZPGRAPH_CSS: string = ${escaped};
`,
  "utf8",
);

console.log("copied style.css → dist/ + src/style-text.ts");
